// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-_T3X4mMEWQHWvX8lMpINa8Yfcct3j0I',
    appId: '1:844098886064:android:6f70a4f6bad93ed0ae1e75',
    messagingSenderId: '844098886064',
    projectId: 'flutter-login-and-regist-53ee1',
    storageBucket: 'flutter-login-and-regist-53ee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6aec5o5hr3oTqDeJMhbPfgBU9uzK_n0',
    appId: '1:844098886064:ios:e28e332c4c910423ae1e75',
    messagingSenderId: '844098886064',
    projectId: 'flutter-login-and-regist-53ee1',
    storageBucket: 'flutter-login-and-regist-53ee1.appspot.com',
    iosClientId: '844098886064-7ftjqdji1bvctj3sic9koq58fbt33qi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginAndRegister',
  );
}
